In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [6]:
x=pd.DataFrame(data=iris['data'],columns=['sepal length in cm','sepal width','petal length','petal width'])

In [8]:
y=iris['target']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [11]:
## apply Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
treeclassifier=DecisionTreeClassifier()

In [12]:
treeclassifier.fit(X_train,y_train)

DecisionTreeClassifier()

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [22]:
treeclassifier.score(X_train,y_train)

1.0

In [23]:
y_predict=treeclassifier.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_predict))
print("===============================")
print(confusion_matrix(y_test,y_predict))
print("===============================")
print(classification_report(y_test,y_predict))



0.9666666666666667
[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.92      0.96        13
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [49]:
print(accuracy_score(y_train,y_predict))

ValueError: Found input variables with inconsistent numbers of samples: [120, 30]

In [31]:
###Prepurning and hyperparameter tunining
grid_param = {
    'criterion': ['gini', 'entropy',],
    'max_depth' : range(2,32,1),
    'min_samples_leaf' : range(1,10,1),
    'min_samples_split': range(2,10,1),
    'splitter' : ['best', 'random'],
    'max_features':['auto','sqrt','log2']
    
}

In [32]:
from sklearn.model_selection import GridSearchCV
grid_searh=GridSearchCV(estimator=treeclassifier,param_grid=grid_param,cv=5)

In [34]:
import warnings
warnings.filterwarnings('ignore')
grid_searh.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 32),
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': range(1, 10),
                         'min_samples_split': range(2, 10),
                         'splitter': ['best', 'random']})

In [41]:
grid_searh.score(X_train,y_train)

0.975

In [35]:
grid_searh.best_params_

{'criterion': 'entropy',
 'max_depth': 18,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 9,
 'splitter': 'random'}

In [36]:
grid_searh.best_score_

0.9833333333333334

In [38]:
hyper_predict=grid_searh.predict(X_test)

In [39]:
accuracy_score(y_test,hyper_predict)

1.0

In [40]:
accuracy_score(y_test,y_predict)

0.9666666666666667

In [42]:
model_with_best_params=DecisionTreeClassifier(criterion='entropy',
 max_depth= 18,
 max_features='sqrt',
 min_samples_leaf= 1,
 min_samples_split= 9,
 splitter ='random')

In [43]:
model_with_best_params.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=18, max_features='sqrt',
                       min_samples_split=9, splitter='random')

In [44]:
best_params_predict=model_with_best_params.predict(X_test)

In [46]:
model_with_best_params.score(X_train,y_train)

0.9416666666666667

In [45]:
accuracy_score(y_test,best_params_predict)

0.9333333333333333

In [48]:
print(accuracy_score(y_test,best_params_predict))
print("===============================")
print(confusion_matrix(y_test,best_params_predict))
print("===============================")
print(classification_report(y_test,best_params_predict))

0.9333333333333333
[[10  0  0]
 [ 0 11  2]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.85      0.92        13
           2       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.93        30
weighted avg       0.95      0.93      0.93        30

